apiVersion: v1
kind: Pod
metadata:
  name: scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    #- --address=127.0.0.1
    - --bind-address=127.0.0.1
    - --authorization-always-allow-paths=[/healthz]
    - --master=https://{{.Hostname}}:{{.K8SAPIServerPort}}
    - --leader-elect=true
    - --profiling=false
    - --v=1
    - --logtostderr=true
    - --kubeconfig=/etc/kubernetes/ssl/kube-scheduler-kubeconfig
    - --authentication-kubeconfig=/etc/kubernetes/ssl/kube-scheduler-kubeconfig
    - --authorization-kubeconfig=/etc/kubernetes/ssl/kube-scheduler-kubeconfig
    - --feature-gates=TTLAfterFinished=true
    image: {{.ImageRegistry}}/{{.ImageRegistryOrg}}/{{.ImageName}}
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - name: registrypullsecret
#    securityContext:
#      runAsUser: {K8S_USER_ID}
#      runAsGroup: {K8S_GROUP_ID}
#      fsGroup: {K8S_GROUP_ID}
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: scheduler
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-path
      readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: {{.KeelHome}}/ssl
    name: ssl-certs-path
