apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --bind-address=127.0.0.1
    - --authorization-always-allow-paths=[/healthz]
    - --master=https://{{.Hostname}}:{{.K8SAPIServerPort}}
    - --leader-elect=true
    - --profiling=false
    - --pod-eviction-timeout=1m0s
    - --service-account-private-key-file=/etc/kubernetes/ssl/kube-serviceaccount.key
    - --root-ca-file=/etc/kubernetes/ssl/ca.crt
    - --v=1
    - --logtostderr=true
    - --kubeconfig=/etc/kubernetes/ssl/kube-controller-kubeconfig
    - --authentication-kubeconfig=/etc/kubernetes/ssl/kube-controller-kubeconfig
    - --authorization-kubeconfig=/etc/kubernetes/ssl/kube-controller-kubeconfig
    - --use-service-account-credentials
#    - --pv-recycler-pod-template-filepath-nfs=/etc/kubernetes/conf/recycler.yaml
    - --flex-volume-plugin-dir=/tmp/kubernetes/kubelet-plugins/volume/exec/
    - --feature-gates=TTLAfterFinished=true
    - --allocate-node-cidrs=true
    - --cluster-cidr={{.PodCIDR}}
    - --node-cidr-mask-size={{.NodeCIDRMaskSize}}
    image: {{.ImageRegistry}}/{{.ImageRegistryOrg}}/{{.ImageName}}
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - name: registrypullsecret
#    securityContext:
#      runAsUser: {K8S_USER_ID}
#      runAsGroup: {K8S_GROUP_ID}
#      fsGroup: {K8S_GROUP_ID}
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: controller
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-path
      readOnly: true
    - mountPath: /etc/kubernetes/conf
      name: config
      readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: {{.KeelHome}}/ssl
    name: ssl-certs-path
  - hostPath:
      path: {{.KeelHome}}/conf/controller-manager
    name: config
