name: sync k8s.gcr.io

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '20 1 * * *'

jobs:
  sync:
    name: sync
    env:
      ALI_REGISTRY_USER: ${{ secrets.ALI_REGISTRY_USER }}
      ALI_REGISTRY_PASS: ${{ secrets.ALI_REGISTRY_PASS }}
      DOCKERHUB_USER: shipengqi
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect docker
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      - name: Inspect go
        run: go version
      - name: pre sync
        run: |
          make build-sync
          /bin/bash .github/scripts/pre-sync.sh
          ${HOME}/sync/synctl sum ${HOME}/sync/sync.bolt.db | wc -l
        env:
          CGO_ENABLED: 0
      - name: sync
        id: sync
        continue-on-error: false
        run: |
          sudo \
          ${HOME}/sync/synctl sync \
          --db ${HOME}/sync/sync.bolt.db \
          -u ${{ secrets.ALI_REGISTRY_USER }} \
          -p ${{ secrets.ALI_REGISTRY_PASS }} \
          --push-ns=keel  \
          --command-timeout ${TIMEOUT:=2h}  \
          --limit ${LIMIT:=3} \
          --image-set ${HOME}/sync/image_set.json
      - name: post sync success
        run: |
          /bin/bash .github/scripts/post-sync.sh
          ls -alh ${HOME}/sync
          ${HOME}/sync/synctl sum ${HOME}/sync/sync.bolt.db | wc -l
        if: steps.sync.outcome == 'success'
      - name: post sync failed
        run: |
          /bin/bash .github/scripts/post-sync.sh
          ls -alh ${HOME}/sync
        if: steps.sync.outcome != 'success'
